# Generated by Django 5.1.3 on 2024-11-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Books', 'Books'), ('Home', 'Home'), ('Hygiene', 'Hygiene'), ('Food', 'Food'), ('Grocery', 'Grocery'), ('Beauty', 'Beauty'), ('Sports', 'Sports'), ('Others', 'Others')], max_length=50),
        ),
    ]
