# Generated by Django 5.1.2 on 2024-10-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_joined_date_person_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=10, null=True)),
                ('college', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(max_length=2, null=True)),
                ('qualification', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
