# Generated by Django 5.1.2 on 2024-10-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
